# This Dockerfile is written for use with goreleaser
FROM gcr.io/distroless/base-debian10

# Copy the static executable built by goreleaser
COPY terraplate /terraplate

# Run as unprivileged user
USER nonroot:nonroot

ENTRYPOINT ["/terraplate"]
CMD ["--help"]