name = "Terraplate"
license = "APACHE-2.0"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Terraplate: DRY Terraform with Go templates."

homepage = "https://github.com/verifa/terraplate"
demosite = "https://terraplate.verifa.io"

tags = ["terraform", "infrastructure-as-code", "documentation"]
features = ["drift detection", "dry terraform", "productivity"]

[author]
  name = "Jacob Lärfors"
  homepage = "https://verifa.io/crew/jlarfors"
